/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Public Public;


typedef struct Prover Prover;

typedef struct Vec_u8 Vec_u8;

typedef struct Verifier Verifier;

uintptr_t sizeof_public(void);

uintptr_t sizeof_prover(void);

uintptr_t sizeof_verifier(void);

struct Prover *prover_new(const Public *ring, uintptr_t ring_len, uintptr_t prover_idx);

struct Vec_u8 *prover_ring_vrf_sign(const struct Prover *prover,
                                    const unsigned char *vrf_input_data,
                                    uintptr_t vrf_input_len,
                                    const unsigned char *aux_data,
                                    uintptr_t aux_data_len);

struct Vec_u8 *prover_ietf_vrf_sign(const struct Prover *prover,
                                    const unsigned char *vrf_input_data,
                                    uintptr_t vrf_input_len,
                                    const unsigned char *aux_data,
                                    uintptr_t aux_data_len);

struct Verifier *verifier_new(const Public *ring, uintptr_t ring_len);

bool verifier_ring_vrf_verify(const struct Verifier *verifier,
                              const unsigned char *vrf_input_data,
                              uintptr_t vrf_input_len,
                              const unsigned char *aux_data,
                              uintptr_t aux_data_len,
                              const unsigned char *signature,
                              uintptr_t signature_len,
                              uint8_t (*result)[32]);

bool verifier_ietf_vrf_verify(const struct Verifier *verifier,
                              const unsigned char *vrf_input_data,
                              uintptr_t vrf_input_len,
                              const unsigned char *aux_data,
                              uintptr_t aux_data_len,
                              const unsigned char *signature,
                              uintptr_t signature_len,
                              uintptr_t signer_key_index,
                              uint8_t (*result)[32]);
